// UTXO errors
pub const UTXO_NOT_FOUND: felt252 = 'UTXO_NOT_FOUND';
pub const UTXO_ALREADY_SPENT: felt252 = 'UTXO_ALREADY_SPENT';
pub const UTXO_ALREADY_LOCKED: felt252 = 'UTXO_ALREADY_LOCKED';
pub const UTXO_NOT_AVAILABLE: felt252 = 'UTXO_NOT_AVAILABLE';
pub const UTXO_INVALID_AMOUNT: felt252 = 'UTXO_INVALID_AMOUNT';
pub const UTXO_BELOW_DUST: felt252 = 'UTXO_BELOW_DUST';
pub const UTXO_MAX_EXCEEDED: felt252 = 'UTXO_MAX_EXCEEDED';
pub const UTXO_DUPLICATE: felt252 = 'UTXO_DUPLICATE';

// Proof errors
pub const INVALID_BITCOIN_PROOF: felt252 = 'INVALID_BITCOIN_PROOF';
pub const INVALID_BITCOIN_TX_PROOF: felt252 = 'INVALID_BITCOIN_TX_PROOF';
pub const PROOF_TOO_OLD: felt252 = 'PROOF_TOO_OLD';
pub const PROOF_ALREADY_USED: felt252 = 'PROOF_ALREADY_USED';
pub const INSUFFICIENT_CONFIRMATIONS: felt252 = 'INSUFFICIENT_CONFIRM';
pub const MERKLE_PROOF_INVALID: felt252 = 'MERKLE_PROOF_INVALID';

// Guardian errors
pub const NOT_GUARDIAN: felt252 = 'NOT_GUARDIAN';
pub const GUARDIAN_ALREADY_EXISTS: felt252 = 'GUARDIAN_ALREADY_EXISTS';
pub const GUARDIAN_NOT_FOUND: felt252 = 'GUARDIAN_NOT_FOUND';
pub const INSUFFICIENT_SIGNATURES: felt252 = 'INSUFFICIENT_SIGNATURES';
pub const THRESHOLD_TOO_HIGH: felt252 = 'THRESHOLD_TOO_HIGH';
pub const THRESHOLD_TOO_LOW: felt252 = 'THRESHOLD_TOO_LOW';
pub const MAX_GUARDIANS_EXCEEDED: felt252 = 'MAX_GUARDIANS_EXCEEDED';

// Withdrawal errors
pub const WITHDRAWAL_NOT_FOUND: felt252 = 'WITHDRAWAL_NOT_FOUND';
pub const WITHDRAWAL_INVALID_STATUS: felt252 = 'WITHDRAWAL_INVALID_STATUS';
pub const WITHDRAWAL_ALREADY_PROCESSED: felt252 = 'WITHDRAWAL_ALREADY_PROCESSED';
pub const WITHDRAWAL_EXPIRED: felt252 = 'WITHDRAWAL_EXPIRED';
pub const WITHDRAWAL_AMOUNT_TOO_LOW: felt252 = 'WITHDRAWAL_AMOUNT_TOO_LOW';
pub const WITHDRAWAL_AMOUNT_TOO_HIGH: felt252 = 'WITHDRAWAL_AMOUNT_TOO_HIGH';
pub const INSUFFICIENT_TOTAL_BTC: felt252 = 'INSUFFICIENT_TOTAL_BTC';
pub const INSUFFICIENT_LIQUIDITY: felt252 = 'INSUFFICIENT_LIQUIDITY';

// Authorization errors
pub const UNAUTHORIZED_VAULT: felt252 = 'UNAUTHORIZED_VAULT';
pub const UNAUTHORIZED_GUARDIAN: felt252 = 'UNAUTHORIZED_GUARDIAN';
pub const UNAUTHORIZED_SWAP_ESCROW: felt252 = 'UNAUTHORIZED_SWAP_ESCROW';
pub const UNAUTHORIZED_RELAYER: felt252 = 'UNAUTHORIZED_RELAYER';

// Bridge errors
pub const BRIDGE_NOT_WHITELISTED: felt252 = 'BRIDGE_NOT_WHITELISTED';
pub const VAULT_PAUSED: felt252 = 'VAULT_PAUSED';
pub const INVALID_BITCOIN_ADDRESS: felt252 = 'INVALID_BITCOIN_ADDRESS';
pub const ZKBTC_MINT_FAILED: felt252 = 'ZKBTC_MINT_FAILED';
pub const ZKBTC_BURN_FAILED: felt252 = 'ZKBTC_BURN_FAILED';