pub const BTC_TX_NOT_FOUND: felt252 = 'BTC_TX_NOT_FOUND';
pub const BTC_TX_INVALID: felt252 = 'BTC_TX_INVALID';
pub const BTC_TX_ALREADY_PROCESSED: felt252 = 'BTC_TX_ALREADY_PROCESSED';
pub const BTC_TX_CONFIRMATIONS_INSUFFICIENT: felt252 = 'BTC_CONFIRM_INSUFFICIENT';
pub const BTC_TX_AMOUNT_MISMATCH: felt252 = 'BTC_AMOUNT_MISMATCH';
pub const BTC_TX_SCRIPT_MISMATCH: felt252 = 'BTC_SCRIPT_MISMATCH';

pub const BTC_PROOF_INVALID: felt252 = 'BTC_PROOF_INVALID';
pub const BTC_PROOF_TOO_OLD: felt252 = 'BTC_PROOF_TOO_OLD';
pub const BTC_PROOF_ALREADY_USED: felt252 = 'BTC_PROOF_ALREADY_USED';
pub const BTC_PROOF_MERKLE_ROOT_MISMATCH: felt252 = 'BTC_MERKLE_ROOT_MISMATCH';
pub const BTC_PROOF_BLOCK_HEADER_INVALID: felt252 = 'BTC_HEADER_INVALID';

pub const BTC_UTXO_NOT_FOUND: felt252 = 'BTC_UTXO_NOT_FOUND';
pub const BTC_UTXO_ALREADY_SPENT: felt252 = 'BTC_UTXO_ALREADY_SPENT';
pub const BTC_UTXO_ALREADY_LOCKED: felt252 = 'BTC_UTXO_ALREADY_LOCKED';
pub const BTC_UTXO_AMOUNT_TOO_LOW: felt252 = 'BTC_UTXO_AMOUNT_TOO_LOW';
pub const BTC_UTXO_AMOUNT_TOO_HIGH: felt252 = 'BTC_UTXO_AMOUNT_TOO_HIGH';

pub const BTC_BRIDGE_PAUSED: felt252 = 'BTC_BRIDGE_PAUSED';
pub const BTC_BRIDGE_NOT_READY: felt252 = 'BTC_BRIDGE_NOT_READY';
pub const BTC_INVALID_ADDRESS: felt252 = 'BTC_INVALID_ADDRESS';
pub const BTC_INVALID_SCRIPT: felt252 = 'BTC_INVALID_SCRIPT';

pub const BTC_VAULT_NOT_SET: felt252 = 'BTC_VAULT_NOT_SET';
pub const BTC_VERIFIER_NOT_SET: felt252 = 'BTC_VERIFIER_NOT_SET';
pub const BTC_TOKEN_NOT_SET: felt252 = 'BTC_TOKEN_NOT_SET';

pub const BTC_UNAUTHORIZED_RELAYER: felt252 = 'BTC_UNAUTH_RELAYER';
pub const BTC_UNAUTHORIZED_GUARDIAN: felt252 = 'BTC_UNAUTH_GUARDIAN';

pub const BTC_INSUFFICIENT_SIGNATURES: felt252 = 'BTC_INSUFFICIENT_SIGNATURES';