// Swap errors
pub const SWAP_NOT_FOUND: felt252 = 'SWAP_NOT_FOUND';
pub const SWAP_ALREADY_EXISTS: felt252 = 'SWAP_ALREADY_EXISTS';
pub const SWAP_INVALID_STATUS: felt252 = 'SWAP_INVALID_STATUS';
pub const SWAP_ALREADY_COMPLETED: felt252 = 'SWAP_ALREADY_COMPLETED';
pub const SWAP_ALREADY_REFUNDED: felt252 = 'SWAP_ALREADY_REFUNDED';
pub const SWAP_ALREADY_EXPIRED: felt252 = 'SWAP_ALREADY_EXPIRED';
pub const SWAP_NOT_ACTIVE: felt252 = 'SWAP_NOT_ACTIVE';
pub const SWAP_NOT_FUNDED: felt252 = 'SWAP_NOT_FUNDED';
pub const SWAP_EXPIRED: felt252 = 'SWAP_EXPIRED';

// Bridge errors
pub const BRIDGE_PAUSED: felt252 = 'BRIDGE_PAUSED';
pub const BRIDGE_NOT_READY: felt252 = 'BRIDGE_NOT_READY';
pub const BRIDGE_TYPE_INVALID: felt252 = 'BRIDGE_TYPE_INVALID';
pub const BRIDGE_LIMIT_EXCEEDED: felt252 = 'BRIDGE_LIMIT_EXCEEDED';

// Amount errors
pub const AMOUNT_TOO_LOW: felt252 = 'AMOUNT_TOO_LOW';
pub const AMOUNT_TOO_HIGH: felt252 = 'AMOUNT_TOO_HIGH';
pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';
pub const INSUFFICIENT_ALLOWANCE: felt252 = 'INSUFFICIENT_ALLOWANCE';
pub const AMOUNT_MISMATCH: felt252 = 'AMOUNT_MISMATCH';

// Time errors
pub const TIMELOCK_NOT_EXPIRED: felt252 = 'TIMELOCK_NOT_EXPIRED';
pub const TIMELOCK_EXPIRED: felt252 = 'TIMELOCK_EXPIRED';
pub const TIMELOCK_TOO_SHORT: felt252 = 'TIMELOCK_TOO_SHORT';
pub const TIMELOCK_TOO_LONG: felt252 = 'TIMELOCK_TOO_LONG';
pub const DEADLINE_PASSED: felt252 = 'DEADLINE_PASSED';

// Hash errors
pub const INVALID_HASHLOCK: felt252 = 'INVALID_HASHLOCK';
pub const INVALID_SECRET: felt252 = 'INVALID_SECRET';
pub const HASHLOCK_MISMATCH: felt252 = 'HASHLOCK_MISMATCH';
pub const SECRET_ALREADY_REVEALED: felt252 = 'SECRET_ALREADY_REVEALED';

// Proof errors
pub const INVALID_PROOF: felt252 = 'INVALID_PROOF';
pub const PROOF_TOO_OLD: felt252 = 'PROOF_TOO_OLD';
pub const PROOF_ALREADY_USED: felt252 = 'PROOF_ALREADY_USED';
pub const INSUFFICIENT_CONFIRMATIONS: felt252 = 'INSUFFICIENT_CONFIRM';
pub const PROOF_VERIFICATION_FAILED: felt252 = 'PROOF_VERIFICATION_FAILED';

// Authorization errors
pub const UNAUTHORIZED_RELAYER: felt252 = 'UNAUTHORIZED_RELAYER';
pub const UNAUTHORIZED_USER: felt252 = 'UNAUTHORIZED_USER';
pub const UNAUTHORIZED_GUARDIAN: felt252 = 'UNAUTHORIZED_GUARDIAN';
pub const UNAUTHORIZED_CANCELLER: felt252 = 'UNAUTHORIZED_CANCELLER';
pub const NOT_SWAP_INITIATOR: felt252 = 'NOT_SWAP_INITIATOR';
pub const NOT_SWAP_COUNTERPARTY: felt252 = 'NOT_SWAP_COUNTERPARTY';

// Contract errors
pub const BTC_VAULT_NOT_SET: felt252 = 'BTC_VAULT_NOT_SET';
pub const SWAP_ESCROW_NOT_SET: felt252 = 'SWAP_ESCROW_NOT_SET';
pub const ZK_VERIFIER_NOT_SET: felt252 = 'ZK_VERIFIER_NOT_SET';
pub const ZKBTC_TOKEN_NOT_SET: felt252 = 'ZKBTC_TOKEN_NOT_SET';
pub const INVALID_CONTRACT_ADDRESS: felt252 = 'INVALID_CONTRACT_ADDRESS';

// Fee errors
pub const FEE_TOO_HIGH: felt252 = 'FEE_TOO_HIGH';
pub const FEE_TOO_LOW: felt252 = 'FEE_TOO_LOW';
pub const FEE_CALCULATION_FAILED: felt252 = 'FEE_CALCULATION_FAILED';
pub const INSUFFICIENT_FEE: felt252 = 'INSUFFICIENT_FEE';

// Retry errors
pub const MAX_RETRIES_EXCEEDED: felt252 = 'MAX_RETRIES_EXCEEDED';
pub const RETRY_TOO_SOON: felt252 = 'RETRY_TOO_SOON';
pub const RETRY_FAILED: felt252 = 'RETRY_FAILED';

// User limits
pub const MAX_PENDING_SWAPS_EXCEEDED: felt252 = 'MAX_PENDING_EXCEEDED';
pub const USER_BLACKLISTED: felt252 = 'USER_BLACKLISTED';
pub const DUPLICATE_SWAP: felt252 = 'DUPLICATE_SWAP';

// Signature errors
pub const INVALID_SIGNATURE: felt252 = 'INVALID_SIGNATURE';
pub const INSUFFICIENT_SIGNATURES: felt252 = 'INSUFFICIENT_SIGNATURES';
pub const SIGNATURE_EXPIRED: felt252 = 'SIGNATURE_EXPIRED';