// Order errors
pub const ORDER_NOT_FOUND: felt252 = 'ORDER_NOT_FOUND';
pub const ORDER_ALREADY_EXISTS: felt252 = 'ORDER_ALREADY_EXISTS';
pub const ORDER_INVALID_SIDE: felt252 = 'ORDER_INVALID_SIDE';
pub const ORDER_INVALID_STATUS: felt252 = 'ORDER_INVALID_STATUS';
pub const ORDER_ALREADY_MATCHED: felt252 = 'ORDER_ALREADY_MATCHED';
pub const ORDER_ALREADY_CANCELLED: felt252 = 'ORDER_ALREADY_CANCELLED';
pub const ORDER_EXPIRED: felt252 = 'ORDER_EXPIRED';
pub const ORDER_NOT_ACTIVE: felt252 = 'ORDER_NOT_ACTIVE';

// User limits
pub const MAX_ORDERS_PER_USER_EXCEEDED: felt252 = 'MAX_ORDERS_USER_EXCEED';
pub const MAX_ACTIVE_ORDERS_EXCEEDED: felt252 = 'MAX_ACTIVE_EXCEEDED';
pub const USER_BLACKLISTED: felt252 = 'USER_BLACKLISTED';

// Amount errors
pub const INVALID_AMOUNT: felt252 = 'INVALID_AMOUNT';
pub const AMOUNT_TOO_LOW: felt252 = 'AMOUNT_TOO_LOW';
pub const AMOUNT_TOO_HIGH: felt252 = 'AMOUNT_TOO_HIGH';
pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';

// Price errors
pub const INVALID_PRICE: felt252 = 'INVALID_PRICE';
pub const PRICE_SLIPPAGE_EXCEEDED: felt252 = 'SLIPPAGE_EXCEEDED';
pub const PRICE_MISMATCH: felt252 = 'PRICE_MISMATCH';

// Commitment errors
pub const INVALID_COMMITMENT: felt252 = 'INVALID_COMMITMENT';
pub const COMMITMENT_MISMATCH: felt252 = 'COMMITMENT_MISMATCH';
pub const COMMITMENT_ALREADY_USED: felt252 = 'COMMITMENT_USED';
pub const NULLIFIER_ALREADY_USED: felt252 = 'NULLIFIER_USED';

// Range proof errors
pub const INVALID_RANGE_PROOF: felt252 = 'INVALID_RANGE_PROOF';
pub const RANGE_PROOF_TOO_LARGE: felt252 = 'RANGE_PROOF_TOO_LARGE';
pub const RANGE_PROOF_EXPIRED: felt252 = 'RANGE_PROOF_EXPIRED';

// Matching errors
pub const NO_MATCHES_FOUND: felt252 = 'NO_MATCHES_FOUND';
pub const MATCH_AMOUNT_TOO_LOW: felt252 = 'MATCH_AMOUNT_TOO_LOW';
pub const MATCH_COUNT_EXCEEDED: felt252 = 'MATCH_COUNT_EXCEEDED';
pub const INVALID_MATCHING_PROOF: felt252 = 'INVALID_MATCHING_PROOF';
pub const ORDER_MISMATCH: felt252 = 'ORDER_MISMATCH';
pub const VOLUME_MISMATCH: felt252 = 'VOLUME_MISMATCH';

// Merkle tree errors
pub const MERKLE_ROOT_MISMATCH: felt252 = 'MERKLE_ROOT_MISMATCH';
pub const MERKLE_PROOF_INVALID: felt252 = 'MERKLE_PROOF_INVALID';
pub const INVALID_MERKLE_PATH: felt252 = 'INVALID_MERKLE_PATH';

// Authorization errors
pub const UNAUTHORIZED_RELAYER: felt252 = 'UNAUTH_RELAYER';
pub const UNAUTHORIZED_CANCELLER: felt252 = 'UNAUTH_CANCELLER';
pub const NOT_ORDER_OWNER: felt252 = 'NOT_ORDER_OWNER';

// Asset errors
pub const UNSUPPORTED_ASSET: felt252 = 'UNSUPPORTED_ASSET';
pub const ASSET_MISMATCH: felt252 = 'ASSET_MISMATCH';

// Expiry errors
pub const INVALID_EXPIRY: felt252 = 'INVALID_EXPIRY';
pub const EXPIRY_TOO_SHORT: felt252 = 'EXPIRY_TOO_SHORT';
pub const EXPIRY_TOO_LONG: felt252 = 'EXPIRY_TOO_LONG';

// System errors
pub const ORDERBOOK_PAUSED: felt252 = 'ORDERBOOK_PAUSED';
pub const CLEANUP_IN_PROGRESS: felt252 = 'CLEANUP_IN_PROGRESS';