// Swap existence errors
pub const SWAP_NOT_FOUND: felt252 = 'SWAP_NOT_FOUND';
pub const SWAP_ALREADY_EXISTS: felt252 = 'SWAP_ALREADY_EXISTS';

// Swap status errors
pub const INVALID_SWAP_STATUS: felt252 = 'INVALID_SWAP_STATUS';
pub const SWAP_NOT_FUNDED: felt252 = 'SWAP_NOT_FUNDED';
pub const SWAP_ALREADY_COMPLETED: felt252 = 'SWAP_ALREADY_COMPLETED';
pub const SWAP_ALREADY_REFUNDED: felt252 = 'SWAP_ALREADY_REFUNDED';
pub const SWAP_ALREADY_EXPIRED: felt252 = 'SWAP_ALREADY_EXPIRED';

// Timelock errors
pub const TIMELOCK_NOT_EXPIRED: felt252 = 'TIMELOCK_NOT_EXPIRED';
pub const TIMELOCK_EXPIRED: felt252 = 'TIMELOCK_EXPIRED';
pub const TIMELOCK_TOO_SHORT: felt252 = 'TIMELOCK_TOO_SHORT';
pub const TIMELOCK_TOO_LONG: felt252 = 'TIMELOCK_TOO_LONG';

// Hashlock errors
pub const INVALID_HASHLOCK: felt252 = 'INVALID_HASHLOCK';
pub const INVALID_SECRET: felt252 = 'INVALID_SECRET';
pub const SECRET_ALREADY_REVEALED: felt252 = 'SECRET_ALREADY_REVEALED';
pub const HASHLOCK_MISMATCH: felt252 = 'HASHLOCK_MISMATCH';

// Authorization errors
pub const UNAUTHORIZED_INITIATOR: felt252 = 'UNAUTHORIZED_INITIATOR';
pub const UNAUTHORIZED_COUNTERPARTY: felt252 = 'UNAUTHORIZED_COUNTERPARTY';
pub const UNAUTHORIZED_RELAYER: felt252 = 'UNAUTHORIZED_RELAYER';

// Amount errors
pub const INVALID_AMOUNT: felt252 = 'INVALID_AMOUNT';
pub const AMOUNT_MISMATCH: felt252 = 'AMOUNT_MISMATCH';
pub const INSUFFICIENT_ALLOWANCE: felt252 = 'INSUFFICIENT_ALLOWANCE';

// Token errors
pub const UNSUPPORTED_TOKEN: felt252 = 'UNSUPPORTED_TOKEN';
pub const TOKEN_TRANSFER_FAILED: felt252 = 'TOKEN_TRANSFER_FAILED';
pub const SAME_TOKEN_NOT_ALLOWED: felt252 = 'SAME_TOKEN_NOT_ALLOWED';

// User limits
pub const MAX_SWAPS_PER_USER_EXCEEDED: felt252 = 'MAX_SWAPS_PER_USER_EXCEEDED';
pub const DUPLICATE_SWAP: felt252 = 'DUPLICATE_SWAP';