// Proof errors
pub const PROOF_TOO_LARGE: felt252 = 'PROOF_TOO_LARGE';
pub const PROOF_INVALID: felt252 = 'PROOF_INVALID';
pub const PROOF_EXPIRED: felt252 = 'PROOF_EXPIRED';
pub const PROOF_ALREADY_USED: felt252 = 'PROOF_ALREADY_USED';
pub const PROOF_NOT_VERIFIED: felt252 = 'PROOF_NOT_VERIFIED';
pub const PROOF_FORMAT_INVALID: felt252 = 'PROOF_FORMAT_INVALID';

// Circuit errors
pub const CIRCUIT_NOT_SUPPORTED: felt252 = 'CIRCUIT_NOT_SUPPORTED';
pub const CIRCUIT_MISMATCH: felt252 = 'CIRCUIT_MISMATCH';
pub const CIRCUIT_CONSTRAINTS_FAILED: felt252 = 'CONSTRAINTS_FAILED';

// Public input errors
pub const INVALID_PUBLIC_INPUTS: felt252 = 'INVALID_PUBLIC_INPUTS';
pub const PUBLIC_INPUTS_TOO_MANY: felt252 = 'PUBLIC_INPUTS_TOO_MANY';
pub const PUBLIC_INPUTS_MISMATCH: felt252 = 'PUBLIC_INPUTS_MISMATCH';

// Batch verification errors
pub const BATCH_SIZE_EXCEEDED: felt252 = 'BATCH_SIZE_EXCEEDED';
pub const BATCH_VERIFICATION_FAILED: felt252 = 'BATCH_VERIFICATION_FAILED';
pub const BATCH_PROOF_INVALID: felt252 = 'BATCH_PROOF_INVALID';

// Order matching errors
pub const ORDER_MISMATCH: felt252 = 'ORDER_MISMATCH';
pub const PRICE_SLIPPAGE_EXCEEDED: felt252 = 'SLIPPAGE_EXCEEDED';
pub const VOLUME_MISMATCH: felt252 = 'VOLUME_MISMATCH';
pub const DUPLICATE_ORDER: felt252 = 'DUPLICATE_ORDER';

// Commitment errors
pub const COMMITMENT_MISMATCH: felt252 = 'COMMITMENT_MISMATCH';
pub const COMMITMENT_ALREADY_USED: felt252 = 'COMMITMENT_USED';
pub const INVALID_COMMITMENT: felt252 = 'INVALID_COMMITMENT';

// Authorization errors
pub const UNAUTHORIZED_VERIFIER: felt252 = 'UNAUTH_VERIFIER';
pub const UNAUTHORIZED_RELAYER: felt252 = 'UNAUTH_RELAYER';
pub const VERIFIER_NOT_WHITELISTED: felt252 = 'VERIFIER_NOT_WHITELISTED';

// Timestamp errors
pub const TIMESTAMP_OUT_OF_RANGE: felt252 = 'TIMESTAMP_OUT_RANGE';
pub const PROOF_TOO_OLD: felt252 = 'PROOF_TOO_OLD';
pub const PROOF_FUTURE_TIMESTAMP: felt252 = 'PROOF_FUTURE';

// Merkle errors
pub const MERKLE_ROOT_MISMATCH: felt252 = 'MERKLE_ROOT_MISMATCH';
pub const MERKLE_PROOF_INVALID: felt252 = 'MERKLE_PROOF_INVALID';
pub const INVALID_MERKLE_PATH: felt252 = 'INVALID_MERKLE_PATH';